### ISSUE TITLE
downloadButton() not working within an F7Page

### ISSUE THREAD

**Issue by bwganblack** [RinteRface/shinyMobile#100]
Not sure if this is a bug or my lack of basic understanding, but both downloadButton() and downloadLink() are unresponsive within an F7Page. Should they work? fileInput() works.

```
library(shiny)
library(shinyMobile)

ui = f7Page(
        f7SingleLayout(
          navbar = f7Navbar(title = "File handling"),
          downloadButton("down1","Download!"),
          downloadLink("down2","Download!"),
          fileInput("up","Upload!")
       )
     )

server = function(input, output) {
  # Our dataset
  data <- mtcars
  
  output$down1 = downloadHandler(
    filename = function() {
      paste("data-", Sys.Date(), ".csv", sep="")
    },
    content = function(file) {
      write.csv(data, file)
    }
  )
  
  output$down2 = downloadHandler(
    filename = function() {
      paste("data-", Sys.Date(), ".csv", sep="")
    },
    content = function(file) {
      write.csv(data, file)
    }
  )
}

shinyApp(ui, server)
```

**Comment by DivadNojnarg** [comment]
In theory, they shouldn't. shinyMobile has its own inputs and vanilla shiny inputs are unlikely to render/work properly

**Comment by bwganblack** [comment]
Ok, thanks David. In that case, is there a shinyMobile method for saving data from an app?

**Comment by ayeTown** [comment]
In my application I use the "RMySQL package and connect to a RDS in AWS. Works well!

**Comment by ayeTown** [comment]
However, I would love to be able to download a markdown report or maybe send an email through the application. That would be pretty awesome.

**Comment by bwganblack** [comment]
Thanks Alice, I will have a look at that method. For now, I am using the built in Buttons extension in `DT::datatable` which facilitates .csv download. It works fine.

**Comment by dewalex** [comment]
I saw this was tagged for v0.8.0.  Is there any idea when that version might be published, or has someone found a workaround for this in the meantime?  I need the user to be able to download a polygon in my application, and am not sure how to accomplish that without the downloadButton().

**Comment by DivadNojnarg** [comment]
The `f7DownloadButton` is implemented:

```r
library(shiny)
 library(shinyMobile)
 ui = f7Page(
  f7SingleLayout(
    navbar = f7Navbar(title = "File handling"),
    f7DownloadButton("download","Download!")
  )
 )

 server = function(input, output, session) {
   # Our dataset
   data <- mtcars

   output$download = downloadHandler(
     filename = function() {
       paste("data-", Sys.Date(), ".csv", sep="")
     },
     content = function(file) {
       write.csv(data, file)
     }
   )
 }
 shinyApp(ui, server)
```

I'll finish the upload part asap

**Comment by dewalex** [comment]
You are my hero.  Thanks so much for getting this going.  

One thing I noted on the phone is that this works fine from Safari, but if you saved it to your homescreen, the popup that is triggered from downloading a file will block your app and have no way to be closed.  Is there a way around that?
