### ISSUE TITLE
Couldn't normalize path error

### ISSUE THREAD

**Issue by ayeTown** [RinteRface/shinyMobile#103]
I'm getting the following error now that I have downloaded the newest version 0.7.0: Warning: Error in value[[3L]]: Couldn't normalize path in `addResourcePath`, with arguments: `prefix` = 'framework7-5.1.1'; `directoryPath` = ''
  [No stack trace available]

**Comment by DivadNojnarg** [comment]
This is weird since `framework7-5.1.1` doesn't exist. Did you have a previous version of shinyMobile installed before? Could you remove all shinyMobile pkgs and reinstall the latest one.

**Comment by ayeTown** [comment]
I deleted the 0.7.0 version of the package and then downloaded 0.1.0 version and I am still getting the same error.

**Comment by DivadNojnarg** [comment]
How do you install the package? 0.7.0 has been submitted to CRAN but not accepted yet. You must use devtools or remotes to install if from GitHub.

**Comment by ayeTown** [comment]
I downloaded shinyMobile version 0.7.0 using devtools (using instructions code). I try to run my app and get that error message. So then I uninstalled shinyMobile version 0.7.0 and installed shinyMobile version 0.1.0 within R Studio (CRAN). Now when I run my app I still get the same error message.

**Comment by ayeTown** [comment]
I just looked in the shinyMobile version 0.1.0 folder. It seems that there is a folder called "framework7-5.1.3". The error refers to "framework7-5.1.1". Maybe you need to change the reference to this folder somewhere in a code file?

**Comment by ayeTown** [comment]
That's what it was. I changed the name of the folder in the shinyMobile folder called "framework7-5.1.3" to "framework7-5.1.1" and now the app runs. However, yall should probably change this.

**Comment by ayeTown** [comment]
I'm also getting the message that the updateF7SmartSelect function does not exist in the 0.7.0 version

**Comment by DivadNojnarg** [comment]
I still don't understand. I downloaded the pkg source from CRAN and Windows/Mac binaries from CRAN and there is no folder 5.1.1. What OS are you using?

**Comment by ayeTown** [comment]
Okay, it's working now. I uninstalled and reinstalled version 0.7.0. It looks like the framework7 folder's name in the package was changed to "framework7-5.5.0". Did you just change that?

**Comment by DivadNojnarg** [comment]
Nope. This was done long time ago

**Comment by ayeTown** [comment]
Guess that's my bad then.
