### ISSUE TITLE
updateF7SmartSelect problem with updating choices

### ISSUE THREAD

**Issue by Edireito** [RinteRface/shinyMobile#107]
Hi, first thanks for the amazing work.

Problem: I have 2 f7SmartSelect and I want the second f7SmartSelect to update the choices depending on the 1 f7SmartSelect but having trouble updating the choices with updateF7SmartSelect.

Is this update in version 0.7.0?

Minimal example:
```r
library(shiny)
library(shinyMobile)

shinyApp(
ui = f7Page(
title = "My app",
f7SingleLayout(
navbar = f7Navbar(title = "Update f7SmartSelect"),
f7Button("updateSmartSelect", "Update Smart Select"),
f7SmartSelect(
inputId = "variable",
label = "Choose a variable:",
selected = "drat",
choices = colnames(mtcars)[-1],
openIn = "popup"
),
tableOutput("data")
)
),
server = function(input, output, session) {
output$data <- renderTable({
mtcars[, c("mpg", input$variable), drop = FALSE]
}, rownames = TRUE)

observeEvent(input$updateSmartSelect, {
  updateF7SmartSelect(
    inputId = "variable",
    openIn = "sheet",
    selected = "cyl",
    choices = c("cyl","teste1"),
    multiple = TRUE,
    maxLength = 3
  )
})
}
)
```

**Comment by ayeTown** [comment]
I think currently you can only updated the selection and not the actual choices of the f7SmartSelect. Is this correct? Want to say thanks to yall as well! This package is awesome!

**Comment by Seyphaton** [comment]
> I think currently you can only update the selection and not the actual choices of the f7SmartSelect. Is this correct? Want to say thanks to yall as well! This package is awesome!

Really, thats definitely a missing feature!
