### ISSUE TITLE
Include logo in header

### ISSUE THREAD

**Issue by Tixierae** [RinteRface/shinyMobile#110]
Just a quick question: is there any option to include a logo in the header? I can't seem to find one. 

With Shiny's `navbarPage`, one can do:

```r
navbarPage(...,
title = tags$a(style='position:fixed;right:10px;top:15px;',tags$img(src='my_logo.png'))
)
```
Also, even though I created a `manifest.json` file, the favicon is still the default one (framework7's). How can I pass my own image?

Thanks in advance for any tip!

**Comment by Seyphaton** [comment]
I always use the default HTML tags:
````
    shiny::tags$head(
        shiny::tags$title("Your Timte")
        ...
````
and for icons
````
    shiny::tags$head(
        shiny::tags$link(rel = "shortcut icon", href = "favicon.png"),
````

**Comment by Tixierae** [comment]
Thank you, but where should these commands be placed? I tried replacing the `title` argument by `shiny::tags$head(shiny::tags$title('my title'))` inside the `f7Page()`, right before `init()`, but it does not work.

**Comment by Tixierae** [comment]
Even adding a `favicon.ico` image in `/www/` as suggested by some comments on this SO [thread](https://stackoverflow.com/questions/30096187/favicon-in-shiny) does not overwrite the default... I still see the framework 7 favicon...

**Comment by Tixierae** [comment]
I just saw https://github.com/RinteRface/shinyMobile/issues/96#issuecomment-610077235 and will try to see if this can solve my problem tomorrow

**Comment by Tixierae** [comment]
About including the logo in the header, the below worked for me:
```r
navbar = f7Navbar(
   title = tags$img(src='my_logo.png',width='200px'),
    ...
)
```
