### ISSUE TITLE
f7AccordionItem pass HTML to title

### ISSUE THREAD

**Issue by Tixierae** [RinteRface/shinyMobile#111]
Is it possible to pass a HTML-formatted title to `f7AccordionItem`?

```r
f7AccordionItem(...,title='<strong>my title</strong>')
```
in the `DT` package for instance, one can control that through the [`escape`](https://shiny.rstudio.com/reference/shiny/0.14/renderDataTable.html) parameter.

Thanks in advance for you help!

**Comment by DivadNojnarg** [comment]
```r
f7AccordionItem(..., title = tags$strong("Item 1"))
 # or 
f7AccordionItem(..., title = HTML("<strong>my title</strong>"))
```

The `HTML` function  is not recommended for security reasons.

**Comment by Tixierae** [comment]
Thanks much for the quick reply and solution!
