### ISSUE TITLE
App setup/initialization issues

### ISSUE THREAD

**Issue by Tixierae** [RinteRface/shinyMobile#112]
Hi, thanks for the amazing package! I am using the following code to initialize my app:

```r
ui = f7Page(
title = 'my title',
icon = './www/favicon.png',
favicon = './www/favicon.png',
manifest = './www/manifest.json',
init = f7Init(
  skin = 'auto',
  theme = 'light',
  filled = TRUE,
  hideNavOnPageScroll = FALSE,
  hideTabsOnPageScroll = FALSE,
  serviceWorker = 'service-worker.js',
  pullToRefresh = FALSE
),...)
```

'my title' is basically the only thing that does work. On the other hand:

1. on my mobile device, **pulling still refreshes the app**, despite the `pullToRefresh = FALSE` above. I noticed the same thing happens in your [demo app](https://dgranjon.shinyapps.io/miniUI2Demo/).

1. none of my icons are recognized. I see placeholders instead. Related to https://github.com/RinteRface/shinyMobile/issues/110 and https://github.com/RinteRface/shinyMobile/issues/96#issuecomment-610077235

1. on my mobile device, it is impossible to zoom in, even on the tabs that just feature HTML text.

1. brownie points: why is a random string like `_w_3fdfc957` appended to the URL of my app when deploying it to shinyapps.io? I noticed the same thing happens with your [demo app](https://dgranjon.shinyapps.io/miniUI2Demo/). The URL appears like `https://dgranjon.shinyapps.io/miniUI2Demo/_w_3fdfc957/`.

I followed the [instructions](https://rinterface.github.io/shinyMobile/) on the package's website to create my `manifest.json`, which looks like:

```json
{
  "name": "my name",
  "start_url": "https://my-url",
  "display": "standalone",
 "icons": [
    {
      "src": "./www/icons/icon-72x72.png",
      "sizes": "72x72",
      "type": "image/png"
    },
  
    {
      "src": "./www/icons/icon-512x512.png",
      "sizes": "512x512",
      "type": "image/png"
    }
  ]
}
```

All my images are there*, in the correct folders, yet **no icons appears**, either in the browser (tab favicon or app UI's header) or when trying to save the app as native (by following the steps [here](https://rinterface.github.io/shinyMobile/#add-the-pwa-to-your-desktop-apps)). I see placeholders instead.
*I know it's not a path problem as some of my images appear fine when loaded with HTML on some tabs.

Thank you in advance for your help!

**Comment by Tixierae** [comment]
actually, my `manifest.json` does not work at all, because when I add the app to my home screen and click the icon, it just opens a tab on my browser, it does not enter the full-screen mode like it does for your demo.
I just found https://github.com/RinteRface/shinyMobile/tree/master/inst/framework7-5.5.0/pwacompat so I will try to just copy the `manifest.json` file that is in there and adapt it to my app. Do I also need to copy the two javascript files into my app directory? The service-worker one maybe?

**Comment by Tixierae** [comment]
Almost all issues fixed! What did the trick for me:

* the `icon`, `favicon`, and `manifest` arguments of `f7Page()` use as root directory the `/www/` folder. Same thing for the icon paths inside `manifest.json`. Previously, all my paths were starting from the app root directory.

* I copied the `pwacompat.min.js` file and adapted-then-copied the `service-worker.js` from [`shinyMobile/tree/master/inst/framework7-5.5.0/pwacompat/`](https://github.com/RinteRface/shinyMobile/tree/master/inst/framework7-5.5.0/pwacompat) to the `/www/` folder of my app.

Now, I can see a favicon in my browser, and an icon when saving the app to home screen on my mobile device, as well as in the splashscreen. The app also runs full-screen on my mobile device :-)

I still could not figure out how to insert an image in the header (navbar) of my app (see https://github.com/RinteRface/shinyMobile/issues/112#), but this is not a big problem.

The big problem that remains (I think this is a bug) is that the `pullToRefresh` argument of `f7Init()` seems to have no effect. But I will create a separate issue for this one.

**Comment by howardbaek** [comment]
I had the same issue today, and resolved it with only the first bullet point:

- the icon, favicon, and manifest arguments of f7Page() use as root directory the /www/ folder. Same thing for the icon paths inside manifest.json. Previously, all my paths were starting from the app root directory.

The second bullet point contains an erroneous link, so I didn't follow it.

**Comment by DivadNojnarg** [comment]
See work in progress: https://divadnojnarg.github.io/outstanding-shiny-ui/mobile-pwa.html and https://divadnojnarg.github.io/outstanding-shiny-ui/mobile-pwa.html

As I am writing the book, I am also reworking `{shinyMobile}` to make the process as smooth as possible. For now, I have issues since the documentation I found online is contradictory.

**Comment by DivadNojnarg** [comment]
@howardbaek : also don't forget to regularly clear your web browser cache since it may keep an old configuration. I happens to me frequently, making me believe my setup was not working

**Comment by howardbaek** [comment]
As I built my own shinyMobile app, I found the documentation to be missing some details. If you wanted, I would gladly help beef up the details of the shinyMobile documentation.

**Comment by DivadNojnarg** [comment]
Sure! The documentation isn’t very good.
