### ISSUE TITLE
rescaling plots / wrapping text when zooming in

### ISSUE THREAD

**Issue by Tixierae** [RinteRface/shinyMobile#115]
I noticed that when zooming in on mobile devices (with the zoom gesture), the content (plots, text, etc.) goes out of page. However, on my laptop, the content is properly rescaled and/or wrapped when zooming-in.
Is there any way to enforce the second behavior (which is more desirable) on mobile devices? Thanks!

**Comment by DivadNojnarg** [comment]
https://stackoverflow.com/questions/995914/catch-browsers-zoom-event-in-javascript.
