### ISSUE TITLE
why does random string get appended to app URL when deployed?

### ISSUE THREAD

**Issue by Tixierae** [RinteRface/shinyMobile#118]
When deploying on shinyapps.io, my URL is not `https://foo.shinyapps.io/my_foo_app/` but `https://foo.shinyapps.io/my_foo_app/_w_0c836d12/`.

Notice the `_w_0c836d12` at the end. I suspect the culprit is shinyMobile, as I have never experienced that with any of my other apps (not relying on shinyMobile).

What is the meaning of such a random string? What are the implications?

Thanks!

**Comment by DivadNojnarg** [comment]
This corresponds to the shinyapps.io worker id. Whenever an R process becomes saturated by clients, a new process is created to guaranty a fluid experience. Nothing harmful.

**Comment by Tixierae** [comment]
Thank you for the explanation. Indeed, I'm seeing now that it happens for all my other apps. It seems this is a new thing.

**Comment by Tixierae** [comment]
Just to let you know and others that actually, that random string appended to the app's URL when not run locally CAN be harmul!!! E.g.: https://community.rstudio.com/t/w-in-shinyapps-io-url/69893

In my case, this was preventing me from consistently passing parameters via session$clientData$url_search, as illustrated here: https://vimeo.com/492431481/d617643247

The solution is to comment out one line in inst/framework7-5.7.8/my-app.js: https://github.com/RinteRface/shinyMobile/blob/344d7df165b7caa48b3a3ed1451f9f0efa189bd0/inst/framework7-5.7.8/my-app.js#L10

One question though: can the line above be safely commented out? Could there be any unanticipated side effect?

Thanks!

**Comment by Tixierae** [comment]
After commenting out `window.history.replaceState`, the tab links are broken and the user cannot navigate the app anymore (see this screencast: https://vimeo.com/493012866/fb3a712dae).
Seems like the tab links are somehow still initialized with the worker ID in them, but then, because of the change above, the worker ID is removed upon first click, causing the links to become broken.
Could you please point me to the script where the tab links are initialized? I could not find it.
Any help would be greatly appreciated, thanks in advance.
