### ISSUE TITLE
Could not find function "f7DownloadButton"

### ISSUE THREAD

**Issue by ayeTown** [RinteRface/shinyMobile#124]
I downloaded the new unreleased version of the library and it is saying that the f7DownloadButton function does not exist. Any idea what's going on here?

**Comment by dewalex** [comment]
I deleted the package and reinstalled it and it was there

**Comment by ayeTown** [comment]
It's there when I look for the function in the Help window... but when I try to use it in an application it, the function is not found.

**Comment by dewalex** [comment]
I updated the package and it wasn't there, but when I went back and removed the package and redownloaded the unreleased version, it appeared after that.
