### ISSUE TITLE
Panel JS events produce very odd behavior

### ISSUE THREAD

**Issue by zac-garland** [RinteRface/shinyMobile#125]
Hi all,

Ran into some odd behavior that seems to be caused by JS/CSS events on the Panels. It also removes ShinyWidgets `pickerInput` formatting all together. 

simple reprex and screenshot below

**normal**

```
library(shiny)
library(shinyMobile)
library(shinyWidgets)


shinyApp(
  ui = fluidPage(
    selectInput("select", "select", choices = letters),
    textInput("text", "text", value = "text"),
    pickerInput("select_2", "select", choices = letters)
  ),
  server = function(input, output) {}
)

```

**shinyMobile**

```
library(shiny)
library(shinyMobile)
library(shinyWidgets)


shinyApp(
  ui = f7Page(
    f7SingleLayout(
      panels = tagList(
        f7Panel(
          side = "left", theme = "light",
          selectInput("select", "select", choices = letters),
          textInput("text", "text", value = "text"),
          pickerInput("select_2", "select", choices = letters)
        )
      ),
      navbar = f7Navbar(left_panel = TRUE),
      toolbar = f7Toolbar()
    )
  ),
  server = function(input, output) {}
)

```

![image](https://user-images.githubusercontent.com/37921090/87732410-247ff000-c78a-11ea-9931-2e310d25d549.png)

**Comment by DivadNojnarg** [comment]
Hi,

shinyMobile has its own pickerInput (f7Picker), selectInput (f7Select), textInput (f7Text) functions.  You can't expect selectInput, textInput and pickerInput to render well since they rely on Bootstrap, while shinyMobile does not. shinyWidgets is not required here:

```r
library(shiny)
library(shinyMobile)


shinyApp(
  ui = f7Page(
    f7SingleLayout(
      panels = tagList(
        f7Panel(
          side = "left", theme = "light",
          f7Select("select", "Select input", choices = letters),
          f7Picker("select_2", "Picker input", choices = letters)
        )
      ),
      navbar = f7Navbar(left_panel = TRUE),
      toolbar = f7Toolbar()
    )
  ),
  server = function(input, output) {}
)
```

**Comment by zac-garland** [comment]
@DivadNojnarg makes sense! shortly after posting I found those inputs and started using them. they do work as intended :) 

just a few comments:

1. nice job man, looks like youve put a lot of work into this, and it works well for its intended purpose!
2. potentially consider changing this https://rinterface.github.io/shinyMobile/articles/Tabs-Layout.html to use the proper f7 inputs rather than shinywidgets inputs to avoid any confusion. 
3. broadly speaking, I see value with being able to switch between bootstrap / f7, e.g. one for mobile, one for desktop. any considerations on trying to integrate the two? could I help?

Best,
Zac
