### ISSUE TITLE
Params in url are removed to load a shinymobile application in shinyapps.io

### ISSUE THREAD

**Issue by ppagnone** [RinteRface/shinyMobile#128]
Hi, congratulations for the excellente package!, 

I am trying to create a shinymobile application with oauth authentication. Locally is working well but I have a problem when this is deployed to shinyapps.io , there the access code received via url is removed when the app is loading.

I saw that shinyMobile is updating the url here when is running in a shinyapp.io: 
https://github.com/RinteRface/shinyMobile/blob/2692ac08a90a63481706722fe6e058431100d788/inst/framework7-5.7.8/my-app.js

and I saw a comment explaining that the objective is to create a new instance when one is saturated. I tried removed but in that case the tab navigation don't work.

Do you think that is possible allow to receive a param via url in a shinymobile ? 

Thanks in advance

**Comment by bwganblack** [comment]
I have seen similar behaviour I think when deployed to shinyapps.io. 

In my case the shinyMobile app loads ok. I then use an f7Link to trigger authentication via a Google web client. I'm then redirected back to my app. I briefly see the security token in the url but it is quickly replaced by an alphanumeric string. 

Authentication seems to work but then renderDatatable and renderUI cease to work.

**Comment by ppagnone** [comment]
@bwganblack  My temporal solution was the following:

In file "inst/framework7-5.7.8/my-app.js" , where the params are removed, I modified the js to keep the hash and search params: 

`   var search = window.location.search;
    var hash = window.location.hash;
    var pathname = window.location.pathname;
    var newpath = pathname + workerId + search + hash;
    window.history.replaceState( {} , 'newpath', newpath);	    
`
But I think will not resolve your problem with DT / renderUI.

**Comment by DivadNojnarg** [comment]
"I saw a comment explaining that the objective is to create a new instance when one is saturated".
Not exactly. If you remove this piece of JS, you will lose the tab navigation. For some reason, I have to get the workerId from shinyapps.io and add it to the url so that navigation works. As far as I understood, people may not be on the same workerId at the same time, especially if the app has temporary high traffic (depends how you configured your app on shinyapps.io). This would also be the case on shiny server pro and rstudio connect. shiny-server open source does not have this issue.

**Comment by DivadNojnarg** [comment]
@bwganblack : could you run the app on desktop and provide a screenshot of the javascript console (F12 or fn + F12 on mac)?

**Comment by bwganblack** [comment]
@DivadNojnarg Hmm, when I was working on this a few months ago, I had the problem with renderUI and DT everytime I tried to authenticate, so I thought it was linked to that issue. Going back to it now, it is occurring inconsistently after attempting to authenticate. So it may be a red herring and not linked to pablo's problem.

Anway, here is a screenshoot when working ok.

![image](https://user-images.githubusercontent.com/14203581/90660894-6fd06700-e23e-11ea-91d5-1004e89f793d.png)

Here is a screenshot when renderUI is not working.

![image](https://user-images.githubusercontent.com/14203581/90661875-9c38b300-e23f-11ea-8dea-d075ffcf9f81.png)

The only difference in the console appears to be the shiny-busy tag, so looks like the app is just hanging sometimes after the redirect.

**Comment by bwganblack** [comment]
@ppagnone Thanks Pablo. I will try this fix out.
@DivadNojnarg When I was working on this a few months ago, I got the renderUI problem everytime I tried to authenticate, but coming back to it now, I am only getting it rarely. I've failed to get a screenshot so far, but the only difference I could see on the console was a `shiny-busy` tag in the html class line at the top. So perhaps the app is sometimes just hanging indefinitely after the redirect?

**Comment by DimadonDL** [comment]
When I deploy my shinyMobile APP to Connect, the search parameter is removed on the iPad when I open the site. On my PC it works.

For examle:

- Start-URL: https://mysite:9999
with Parmater: https://mysite:9999/?info=test

How can I handle this problem? When I modify the APP.js  like @ppagnone post, it works but then the navigation does not work anymore and the dark theme is gone.

**Comment by DimadonDL** [comment]
Now I changed the pathname in APP.js to the full Path. This way works at least for me.

**Comment by ppagnone** [comment]
@DimadonDL I had some problems with dark theme too, Do you say that you could resolve replacing "window.location.path" with "window.location.href" ?   Did you test it in shinyapps.io ? 
Thanks in advance

**Comment by DimadonDL** [comment]
@ppagnone This is exactly what helped me, but I use connect for the deployment. For me it was the phenomenon that the search parameter worked when using the app on a PC. But with an iPad it was always deleted. By adjusting with "window.location.href" the search parameter is now preserved and everything works fine. I cannot say if it works with shinyapps.io in the same way.
