### ISSUE TITLE
updateF7Radio

### ISSUE THREAD

**Issue by korterling** [RinteRface/shinyMobile#135]
is there updateF7Radio function?
or
if the current version does not have a updateF7Radio function,

how to create a updateF7Radio,any suggestion?

**Comment by yangbenfa** [comment]
updateF7Radio <- function (inputId, label = NULL, choices = NULL,selected = NULL, session = shiny::getDefaultReactiveDomain()) 
{
  message <- list(label = label, choices = choices,selected = selected)
  session$sendInputMessage(inputId, message)
}

but this not effective

**Comment by korterling** [comment]
thanks,i solved this issue,tks

**Comment by korterling** [comment]
any suggestion?

**Comment by DivadNojnarg** [comment]
I unfortunately did not have time to finish it, and as you noticed, the function does not work at the moment. I won't have time in a near future as well.

**Comment by korterling** [comment]
I fork your repositories and  wrap a new function ,as below:

updateF7Radio <- function (inputId, label = NULL,
                           choices = NULL,selected = NULL,
                           session = shiny::getDefaultReactiveDomain()) {
  if (!is.null(selected)) {
    if (length(selected) == 1) {
      selected <- list(as.character(selected))
    } else {
      selected <- as.character(selected)
    }
  }

  message <- dropNulls(list(label = label,
                            choices = choices,
                            selected = selected))
  session$sendInputMessage(inputId, message)
}

then reinstall the package,
but it does not work,what is wrong?
