### ISSUE TITLE
f7DatePicker displaying yesterday when value = Sys.Date()

### ISSUE THREAD

**Issue by ferguskeatinge** [RinteRface/shinyMobile#138]
Small bug in the f7DatePicker when the value is designated as Sys.Date().

f7DatePicker(inputId = "start_date", label = NULL, value =  Sys.Date(), min = "2020-01-01", max = Sys.Date()+14, multiple = FALSE, direction = "vertical")

Today is 11/19/2020 but the UI is displaying the previous day:

![image](https://user-images.githubusercontent.com/12262076/99665087-25c27180-2a37-11eb-9465-567fff3e18fb.png)

Sys.Date() text color has been changed to blue, but the blue circle is surrounding the previous day.

![image](https://user-images.githubusercontent.com/12262076/99665212-50acc580-2a37-11eb-9033-f072f4886983.png)

The input$start_date value on the server side is resulting in the previous day also.

**Comment by DivadNojnarg** [comment]
Fixed in latest devel version:

```r
remotes::install_github("RinteRface/shinyMobile")
```
