### ISSUE TITLE
Changing icon that opens panel

### ISSUE THREAD

**Issue by bklingen** [RinteRface/shinyMobile#159]
I would like to change the bar icon that appears when defining a right panel to, say, a question_circle icon. Is this possible?
I see where the icon is defined when inspecting the element (see picture below), but how do I change this programmatically?
(I tried adding `icon = f7Icon("question_circle")` inside `f7Panel`, which defines the content of the right panel, but that just puts the icon in the panel.)

```r
library(shiny)
library(shinyMobile)
shinyApp(
  ui = f7Page(
    f7SingleLayout(
      navbar = f7Navbar(
        title = "Change Icon?",
        rightPanel = TRUE
      )
    )
  ),
  server = function(input, output) {}
)
```
![image](https://user-images.githubusercontent.com/4784206/109366917-a8db3b00-7862-11eb-9bd8-4ad6d2812bcf.png)

**Comment by DivadNojnarg** [comment]
Thanks for the suggestion. This is a cool idea, I'll try to get it soon
