### ISSUE TITLE
insertF7Tab fails when including Tab Content

### ISSUE THREAD

**Issue by cofrca** [RinteRface/shinyMobile#174]
Thank you for fixing the icon problem on `insertF7Tab()`! I noticed another little bug.

On the standard example; `insertF7Tab()`  works well including icon, but when tab content is added, an error is given and the example app crashes.
 `tab = f7Tab (tabName = "test", "Test", f7Button(inputId = "stay", label = "Stay") )`  gives the following error and leads to a crash.
> `Warning: Error in writeImpl: Text to be written must be a length-one character vector` 

Version 1.0.0.9000. 
Thank you!

**Comment by dmenne** [comment]
I will check this, thanks for reporting the issue.

**Comment by dmenne** [comment]
I could not reproduce the behavior with the current version, but there are pending pull requests currently. Could you please try to run the sample in /inst/examples/dynamic_tab on the github version in my repository?

```
devtools::install_github("dmenne/shinyMobile@devel")

**Comment by cofrca** [comment]
Hi - thanks for the quick response!

On the sample in /inst/examples/dynamic_tab  - changing line 42 to `observeEvent(input$add, {` lets the button add two new tabs.

The problem I am still encountering is when I try to include tab content in the one being added - in this case "Test1" or "Test2"

**Comment by dmenne** [comment]
Confirmed. Will check.

**Comment by dmenne** [comment]
Give it another try; I have change the example to multiple  controls, but it is still open if this will work for deeper nested cases.

**Comment by cofrca** [comment]
Thank you for your updates! I've been poking around at what is and what isn't working. This is what I've found:


The buttons and inputs render well on the new page, but I couldn't get the new button to do anything. The text input is displayed but I'm having trouble using the corresponding input$id in the server. Also, renderUI elements from the server are not displaying. Is this a namespace problem or something deeper?

The other thing I noticed was where the tab's label was coming from (see lines 31 and 52 in the included example)
[stressed_tabs.zip](https://github.com/RinteRface/shinyMobile/files/6150842/stressed_tabs.zip)

**Comment by dmenne** [comment]
Looks like https://github.com/RinteRface/shinyMobile/issues/134

I am only a very recent user forced to get this working... @DivadNojnarg is very busy, and cannot work on the project currently, as he reported. Maybe we can get someone interested at Novartis, who seems to be the original sponsor, to have someone continue the work.

**Comment by cofrca** [comment]
Ah, yes that does look like [#134](https://github.com/RinteRface/shinyMobile/issues/134) - sorry for the overlap.

I definitely appreciate your help! 
It looks like in the meantime I'll try using `removeF7Tab()` as well as `updateF7Tabs()` with hidden tabs as a workaround.

**Comment by DivadNojnarg** [comment]
Hi, the reactivity is lost after inserting a tab. The work that needs to be done is described here: https://unleash-shiny.rinterface.com/custom-templates-interactivity.html#insert-tabs. This involves to wrap the newly inserted content in a `shiny:::processDeps` call and render the dependencies on the JS side.

**Comment by DivadNojnarg** [comment]
@cofrca : I added a patch to allow input/output in the inserted tab. This fixes the broken reactivity issue:

```r
library(shiny)
library(shinyMobile)
shinyApp(
  ui = f7Page(
    title = "Insert a tab Before the target",
    f7TabLayout(
      panels = tagList(
        f7Panel(title = "Left Panel", side = "left", theme = "light", "Blabla", effect = "cover"),
        f7Panel(title = "Right Panel", side = "right", theme = "dark", "Blabla", effect = "cover")
      ),
      navbar = f7Navbar(
        title = "Tabs",
        hairline = FALSE,
        shadow = TRUE,
        leftPanel = TRUE,
        rightPanel = TRUE
      ),
      f7Tabs(
        animated = TRUE,
        id = "tabs",
        f7Tab(
          tabName = "Tab 1",
          icon = f7Icon("airplane"),
          active = TRUE,
          "Tab 1",
          f7Button(inputId = "go", label = "Go")
        ),
        f7Tab(
          tabName = "Tab 2",
          icon = f7Icon("today"),
          active = FALSE,
          "Tab 2"
        )
      )
    )
  ),
  server = function(input, output, session) {
    observeEvent(input$go, {
      insertF7Tab(
        id = "tabs",
        position = "before",
        target = "Tab 1",
        tab = f7Tab(
          tabName = paste0("tab_", input$go), 
          f7Slider("obs", "Number of observations:",
                      min = 0, max = 1000, value = 500
          ),
          plotOutput("distPlot"),
          icon = f7Icon("app_badge_fill")
        ),
        select = FALSE
      )
      output$distPlot <- renderPlot({
        hist(rnorm(input$obs))
      })
    })
  }
)

```

**Comment by cofrca** [comment]
@DivadNojnarg Thank you for your replies and time. Reading about the interactivity and `processDeps` helped me understand the process a bit better. I'm still learning and I appreciate your help!
When running the example, I'm still getting an error:
> Warning: Error in : 'createWebDependency' is not an exported object from 'namespace:htmltools'
[does that trace back to R/utils.R](https://github.com/RinteRface/shinyMobile/commit/e0ba0a3318d45c6f9702d1c3c4dcaa22eed21830#r48330695)
