### ISSUE TITLE
Add 'id' argument to f7Card

### ISSUE THREAD

**Issue by nathhenry3** [RinteRface/shinyMobile#176]
Hi there,

I was wondering if it's possible for an 'id' argument to be added to the f7Card() function? It would be great to have the ability to toggle the card's visibility with shinyjs::hidden() or similar.

Let me know if there is an easy way to implement this, and I'll try do it myself if so.

Thanks a lot!

**Comment by cofrca** [comment]
Hi @nathhenry3 

In case you're still working on this, it seemed like the `f7Card(id = "designatedID", ... )` worked for me. Another option is to wrap it in a `tags$div()` with the id set. Another idea is to use `uiOutput() and renderUI()`. 

I've included an example that uses `removeUI()` as well as `uiOutput() and renderUI()`

> library(shiny)
library(shinyMobile)
shinyApp(
  ui = f7Page(
    f7TabLayout(
      panels = NULL,
      navbar = f7Navbar(title = "EXAMPLE FOR YOU"),
      f7Tabs(
        id = "tabset",
        f7Tab(
          tabName = "Cool Tab",
          icon = f7Icon("smiley"),
          active = TRUE,
          f7Toggle( inputId = "toggle", label = "Turn on/off dynamic card", 
            color = "pink", checked = FALSE ),
          hr(),
          f7Card(
            id = "tunacakes",
            h4("This is a happy f7Card until that button is pushed")%>% f7Align(side = "center"),
            br(),
            f7Text( inputId = "whatever", label = NULL, placeholder = "Type type type" ),
            br(),
            f7Button( "delete_button", "DELETE THIS", color = "red")
          ),
          uiOutput("dynamic_card")
        )
      )
    )
  ),
  server = function(input, output, session) {
    # This section deletes the first (red) card ----
    observeEvent(input$delete_button,{ removeUI("#tunacakes") })
    # This section controls the second (orange) card ----
    observeEvent(input$delete_buttonv2,{ removeUI("#tunacakesv2") })
    output$dynamic_card <- renderUI(
      if (input$toggle == TRUE){
        f7Card(
          id = "tunacakesv2",
          h2("This is another happy f7Card")%>% f7Align(side = "center"),
          br(),
          f7Text( inputId = "whateverv2", label = NULL, placeholder = "Type type type" ),
          br(),
          f7Button( "delete_buttonv2", "DELETE THISv2", color = "orange")
        )
      } else{}
    )
  }
)

**Comment by DivadNojnarg** [comment]
Adding `id` inside `f7Card` applies the id only to the card body and not the footer nor the header. To be exact, I would apply the `id` at the top level as shown below using `<TAG>$attribs$id`, where `<TAG>` is the f7Card shiny tag:

```r
library(shiny)
library(shinyMobile)
library(dplyr)

customCard <- f7Card(
  h4("This is a happy f7Card until that button is pushed")%>% f7Align(side = "center"),
  br(),
  f7Text( inputId = "whatever", label = NULL, placeholder = "Type type type" ),
  br(),
  f7Button( "delete_button", "DELETE THIS", color = "red")
)

customCard$attribs$id <- "designatedID"

shinyApp(
  ui = f7Page(
    f7TabLayout(
      panels = NULL,
      navbar = f7Navbar(title = "EXAMPLE FOR YOU"),
      f7Tabs(
        id = "tabset",
        f7Tab(
          tabName = "Cool Tab",
          icon = f7Icon("smiley"),
          active = TRUE,
          f7Toggle( inputId = "toggle", label = "Turn on/off dynamic card", 
                    color = "pink", checked = FALSE ),
          hr(),
          customCard,
          uiOutput("dynamic_card")
        )
      )
    )
  ),
  server = function(input, output, session) {
    # This section deletes the first (red) card ----
    observeEvent(input$delete_button,{ removeUI("#designatedID") })
  }
)
```

**Comment by cofrca** [comment]
Thank you @DivadNojnarg, using `<TAG>$attribs$id` is a much better idea than any of my workarounds. That helped fix a problem that I didn't even realize I had, as _most_ of my dynamic f7Cards didn't include footers - So I hadn't noticed anything.
