### ISSUE TITLE
Need help with chat widget

### ISSUE THREAD

**Issue by DillonAlice** [RinteRface/shinyMobile#177]
Hi, the chat widget demo works when I run it as it is (i.e. with the database details the author provided). But after changing the database details, it keeps showing an error message. I tried using Google Cloud SQL and AWS RDS, and both gave the same error message below. Also tried all the suggestions on the web, like changing inbound rules on RDS, but nothing works. 

The error message:
Listening on http://127.0.0.1:5342
Warning: Error in : Failed to prepare query: ERROR:  relation "messages" does not exist
LINE 1: SELECT * FROM  "messages"

The only part of the chat widget demo I changed are the database details:
con <- DBI::dbConnect(
          RPostgres::Postgres(),          
          dbname = "xxx",
          host = "xxx",
          port = "5432",
          user = "xxx",
          password = "xxx"
        )

Would appreciate any help. And thanks to the author for creating such a wonderful package, really appreciate it!

**Comment by dmenne** [comment]
Could you please point me to the location in the code of shinyMobile? Could it be that you posted on the wrong forum?

**Comment by DillonAlice** [comment]
Dear Dieter, thanks for taking time to reach out. I'm a huge fan of your shinyMobile package, it is so awesome! ♥  

Below is the chat widget code from your package I'm using, I only changed your postgres details with mine and changed mclapply to lapply (because mclapply didn't work on mine), the rest of the codes are unchanged. I'm sure I'm not doing something right but I just can't figure out where... I'll appreciate any words of advice, thank you :)

library(shiny)
library(shinyMobile)
library(DBI)
library(dplyr)
library(tibble)
library(parallel)

shinyApp(
  ui = f7Page(
    title = "shinyChat",
    allowPWA = TRUE,
    f7SingleLayout(
      navbar = f7Navbar(
        title = "shinyChat",
        hairline = FALSE,
        shadow = TRUE,
        transparent = TRUE,
        bigger = TRUE
      ),
      toolbar = f7MessageBar(inputId = "mymessagebar", placeholder = "Message"),
      # main content
      f7Messages(id = "mymessages", title = "Chat Room")

    )
  ),
  server = function(input, output, session) {

    messages_table <- reactiveValues()
    firstConnect <- reactiveVal(TRUE)

    observe({
      f7Dialog(
        type = "prompt",
        text = "Enter your name",
        id = "nickname"
      )
    }, priority = 100)

    # load messages first
    observe({
      # load all messages
      if (firstConnect()) {
        req(input$nickname)
        con <- DBI::dbConnect(
          RPostgres::Postgres(),

dbname = "xxx",
host = "xxx",
port = "5432",
user = "xxx",
password = "xxx"
                    
             # dbname = "deminr",
             # host = "46.101.117.230",
             # port = "5432",
             # user = "divad",
             # password = "prout"
        )

        # Get the messages
        messages_table$table <- DBI::dbReadTable(con, "messages")
      
        messages <- lapply(seq_len(nrow(messages_table$table)), function(i) {
          temp_message <- messages_table$table %>% dplyr::slice(i)

          f7Message(
            text = temp_message$message,
            header = temp_message$date,
            name = temp_message$nickname,
            type = if (input$nickname == temp_message$nickname){
              "sent"
            } else {
              "received"
            },
            avatar = "https://cdn.framework7.io/placeholder/people-100x100-9.jpg"
          )
        })

        updateF7Messages(id = "mymessages", messages)

        firstConnect(FALSE)
        # Disconnect from database
        DBI::dbDisconnect(con)
      }
    })

    # send message part
    observeEvent(input[["mymessagebar-send"]], {
      message_to_send <- f7Message(
        text = input$mymessagebar,
        name = input$nickname,
        type = "sent",
        header = Sys.time(),
        avatar = "https://cdn.framework7.io/placeholder/people-100x100-9.jpg"
      )

      updateF7Messages(
        id = "mymessages",
        list(message_to_send),
        showTyping = TRUE
      )

      con <- DBI::dbConnect(
        RPostgres::Postgres(), 

dbname = "xxx",
host = "xxx",
port = "5432",
user = "xxx",
password = "xxx"
                
        # dbname = "deminr",
        # host = "46.101.117.230",
        # port = "5432",
        # user = "divad",
        # password = "prout"
      )

      # Convert to tibble to tidy data
      # DB column names are different
      # We need to do some cleaning
      message_to_send <- message_to_send %>%
        as_tibble() %>%
        select(name, text, header) %>%
        rename(nickname = "name", message = "text", date = "header")

      DBI::dbAppendTable(con, name = "messages", value = message_to_send)
      messages_table$table <- DBI::dbReadTable(con, name = "messages")
      DBI::dbDisconnect(con)
    })
  }
)

After running the above with my Google Cloud SQL details, I'll get this error:
Warning: Error in : Failed to prepare query: ERROR: relation "messages" does not exist
LINE 1: SELECT * FROM "messages"

**Comment by dmenne** [comment]
The praise goes to David, I am just a user who did some add-ons for my own used and made some minor changes to the published code. I will have a look.

**Comment by dmenne** [comment]
Could it be that table "messages" does not exist in your database? Or maybe it is there, but your connection string got the database wrong?

```
DBI::dbListTables(con)
```

**Comment by DillonAlice** [comment]
Dear Dieter, thanks for your reply. When I tried DBI::dbListTables(con), it gave character(0).  I must be doing something wrong with my database, but as I only started learning about PostgreSQL yesterday, I'm still very confused. Will go read up more on how database work and also follow your suggestion to check the connection string. 

If I manage to find the solution, will update here. Thanks for being so nice and helpful with my question. And a big thank you to you and David for producing great work that the rest of us get to enjoy! 👍

**Comment by DivadNojnarg** [comment]
Hi Alice, thanks for using the package ;)

If I understand correctly, you're trying to create your own DB? Did you enable the corresponding port on your server? Is your `messages` table setup?

This is how I created the Postgr DB:

```sql
CREATE TABLE messages (
  nickname varchar NOT NULL,
  message varchar NOT NULL,
  date varchar NOT NULL
);

INSERT INTO messages (nickname, message, date) VALUES ('bobby', 'My amazing message', '2020-03-04');
```

Quite honestly, I don't really like the current system as it implicitly relies on `{httpuv}`. `httpuv` is used by `shiny` to establish the R/JS communication within one user session, so definitely not suitable for a chat. Indeed, in a normal chat, you would expect to see people's message without having to refresh, which is not the case here since `{httpuv}` is not able to do multi casting over multiple clients (makes total sense in shiny's context ;), as it would be a huge mess): see more here: https://unleash-shiny.rinterface.com/shiny-intro.html 

A real chat system would imply a separate websocket, the server being created with a multi cast compatible technology: https://betterprogramming.pub/build-a-chat-app-in-node-js-with-room-functionality-6ebbd4b19133. You would also have to create a shiny component that connects to this extra server websocket  (I say extra because Shiny already established 1 websocket connection, as previously mentioned). Finally store all messages in a database. 

Overall, it's not that easy for end users to get a real chat.

**Comment by DillonAlice** [comment]
Dear David, you're a godsend! Thanks for taking time to leave such a detailed answer, you're spot on, I was so stupid not to realize I need to create a table first and also enable the port, and thanks so much for sharing your code for creating the table, it is very helpful for this newbie!  I have managed to get it up and running all thanks to you 👍 

Once again, thanks for being so generous with your time in creating this wonderful package and helping to answer my silly question, you are just amazing!!
