### ISSUE TITLE
shinyTest has problems finding control

### ISSUE THREAD

**Issue by dmenne** [RinteRface/shinyMobile#178]
In our application, there is a requirement by the sponsor that basic functions should be tested with `shinytest`. We are using `shinytest for standard shiny application successfully, but I have not been able to get it to pass f7 application`s. I tried with the example app for `singleLayout` in the documentation. 

- There is a limitation in shinytest that a single app file must be named `app.R`
- Run `shinytest::recordTest`. Take snapshot, enter value. Take snapshot. Works ok
- When the test is run, there is an error message:

`Running mytest.R Fehler in session_makeRequest(self, private, endpoint, data, params, headers) : 
  Unable to find input binding for element with id obs`

Which refers to :

` f7Slider("obs", "Number of observations", 0, 1000, 500),`

This is just an example, other apps give similar errors. I assume `shinyMobile` is not using conventional naming of ids. I presume the problem with non-responding dynamic elements might be related.

**Comment by DivadNojnarg** [comment]
It's more on the `{shinytest}`side. It is made to only work with vanilla shiny elements and maybe not all: https://github.com/rstudio/shinytest/issues/369. Below is the list of elements that work, that belong to a predefined mapping file:

```r
widget_names <- c(
    "shiny.actionButtonInput"  = "actionButton",
    "shiny.checkboxInput"      = "checkboxInput",
    "shiny.checkboxGroupInput" = "checkboxGroupInput",
    "shiny.dateInput"          = "dateInput",
    "shiny.dateRangeInput"     = "dateRangeInput",
    "shiny.fileInputBinding"   = "fileInput",
    "shiny.numberInput"        = "numericInput",
    "shiny.radioInput"         = "radioButtons",
    "shiny.selectInput"        = "selectInput",
    "shiny.sliderInput"        = "sliderInput",
    "shiny.textInput"          = "textInput",
    "shiny.passwordInput"      = "passwordInput",
    "shiny.bootstrapTabInput"  = "tabsetPanel",

    "shiny.textOutput"         = "textOutput",
    "shiny.verbatimTextOutput" = "verbatimTextOutput",
    "shiny.htmlOutput"         = "htmlOutput",
    "shiny.imageOutput"        = "plotOutput",
    "datatables"               = "tableOutput"
  )
```

On a side note: `{shinytest}` does not work well with Bootstrap 4 (due to the outdated `phantomjs`), which is an issue if you think about the `{shiny}` BS4 migration. 

For custom templates, I personally rely on `{crrry}` to test the user interface and JS behavior.

**Comment by DivadNojnarg** [comment]
A `{crrry}` example: https://unleash-shiny.rinterface.com/custom-templates-testing.html#testing-template-behavior

**Comment by dmenne** [comment]
Thanks for pointing me to crrry, which I did not know (I should have read unleash to the end, I admit).

D

**Comment by dmenne** [comment]
Looks like crrry is special for custom templates:

https://github.com/ColinFay/crrry/issues/7

**Comment by dmenne** [comment]
Using you example in "unleash" works - I have posted it on the ColinFay page. This is inconsistent behavior in crrry, but not an issue of shinyMobile
