### ISSUE TITLE
Rendering a value or info box

### ISSUE THREAD

**Issue by khbrc** [RinteRface/shinyMobile#185]
Hi,
Is it possible to directly render a valuebox?  I can insert a valuebox but it just displays as ordinary text.  Or is there a way of doing it that I'm missing or does something equivalent exist in shinyMobile?

Regards,
Kathleen

**Comment by khbrc** [comment]
While rendering a valuebox or infobox would still be quite handy, I found the list option isn't a bad alternative.  Thanks.

Regards,
Kathleen

**Comment by DivadNojnarg** [comment]
Hi,

valueBox and infoBox are part of the `{shinydashboard}` package, which is not supported by `{shinyMobile}`. The idea is interesting however. I keep it as a side note.

**Comment by khbrc** [comment]
Thanks. I really appreciate that.  And thanks for the package, it's been fun trying it out!
