### ISSUE TITLE
.Deprecated in f7Checkbox

### ISSUE THREAD

**Issue by stamats** [RinteRface/shinyMobile#186]
Many thanks for your package!

I found one issue:

.Deprecated("f7Checkbox", package = "shinyMobile", "f7checkBox will be removed in future release. Please use\n    f7Checkbox instead.", 
        old = as.character(sys.call(sys.parent()))[1L])

should be removed in the new function f7Checkbox. The respective call to .Deprecated should only be included in the old version f7checkBox otherwise you also get a warning when you already use the new function.

Best Matthias

**Comment by dmenne** [comment]
Oops, I thought I had found all culprits of that sort. I will create a pull request.

Thanks.

**Comment by dmenne** [comment]
PR done. Waiting for merge

**Comment by DivadNojnarg** [comment]
Merged yesterday.
