### ISSUE TITLE
How to add a longer dialog for f7Dialog

### ISSUE THREAD

**Issue by moldach** [RinteRface/shinyMobile#190]
I'm hoping to add a longer **Terms of Use** section to my application using `f7Dialog()` but at some point beyond this, there is no **scroll-bar** which prevents the user from selecting the prompt to close the dialog.

It would be helpful to include a scroll-able widget function in this function to display lengthy messages.

## On Desktop

![f7Dialog-longer](https://user-images.githubusercontent.com/5749465/116834989-c6d45d00-ab7d-11eb-8ef8-33ad4928fc04.PNG)

## Deployed and viewed on mobile

![nk2ZY4HA](https://user-images.githubusercontent.com/5749465/116835319-297a2880-ab7f-11eb-9e5c-2daddf816c16.jpeg)

**Comment by cofrca** [comment]
Hi @moldach, in using `f7Dialog()`, I've found that the text argument takes a `shiny::HTML()` with whatever html you'd like in it.

This is a rough example but it shows a scrollable f7dialog:

```r
library(shiny)
library(shinyMobile)
shinyApp(
  ui = f7Page(
    title = "Simple Dialog",
    f7SingleLayout(
      navbar = f7Navbar(title = "f7Dialog"),
      f7Button(inputId = "goButton", "Go!")
    )
  ),
  server = function(input, output, session) {
    observeEvent(input$goButton,{
      f7Dialog(
        title = "Dialog title",
        text = HTML("<h3> h3 title </h3>
                    
                    
                    <div style=\"height:150px;overflow:scroll;\">
Lorem ipsum dolor sit amet. Eum consequuntur fugiat ab Quis quia aut ipsam optio non voluptatum nihil. Et culpa omnis est enim aliquam sed cumque quibusdam! Aut odit ullam aut galisum veritatis 33 placeat obcaecati ut consequatur consequatur est consectetur minima ut expedita ullam.

Et accusantium dignissimos hic cupiditate saepe in tempora fugiat sit galisum blanditiis ex ducimus fugit sit rerum reiciendis sed perspiciatis voluptas. Est voluptas doloribus in quisquam hic sunt maxime cum maiores Quis ea modi corporis eos magni accusamus in ratione doloribus. Hic veritatis atque non galisum quibusdam cum quisquam dicta in atque velit.
</div>      
                    ")
      )
    })
  })
```

Not the most elegant looking example, but with some tweaking and .css you might find something to your liking
