### ISSUE TITLE
f7SmartSelect: make closeOnSelect=TRUE work with multiple=TRUE and maxlength=1

### ISSUE THREAD

**Issue by Tixierae** [RinteRface/shinyMobile#198]
Hi! In the news, you mention that thanks to fix #144, it is now possible to close the smart select when the user has made a selection. I imagine that this can be done by passing an argument in the new "`,...`" additional arguments section at the end.

I looked it up [online](https://www.tutorialspoint.com/framework7/forms_smart_select.htm) and in framework 7, that argument is called `data-back-on-select`. What is the corresponding argument name in Shiny? I tried `backOnSelect` but it does not seem to work.

Thanks!

**Comment by DivadNojnarg** [comment]
You should have a look to the official Framework7 documentation. The argument is called closeOnSelect. https://v5.framework7.io/docs/smart-select.html#smart-select-parameters

**Comment by Tixierae** [comment]
Many thanks for the quick and helpful reply! I had not realized I was not looking at the official documentation, my bad.

I had to set `multiple=TRUE` and `maxlength=1` because I am working on a form and I want to make sure every recorded response is due to user action, and not just something that has been left at its default value (with `multiple=FALSE`, the first choice is pre-selected).

Is there any way to make `closeOnSelect=TRUE` work with `multiple=TRUE` and `maxlength=1`?

Thanks
