### ISSUE TITLE
Suggestion: avoid using inline CSS so that users can easily override {shinyMobile} defaults

### ISSUE THREAD

**Issue by daattali** [RinteRface/shinyMobile#219]
There are places in the code where inline styles are used, for example tabs have an inline background colour https://github.com/RinteRface/shinyMobile/blob/93eaffee6a8941376802ae867add36407531e19d/R/f7-tabs.R#L362

This means that it's difficult to override this style and we must use `!important`. If a CSS class is used instead of an inline style it would be more user friendly.

**Comment by jpiaskowski** [comment]
ah, this might explain some difficult I'm having adjusting the panel menu background color! Thanks for the potential tip.
