### ISSUE TITLE
how to change the theme

### ISSUE THREAD

**Issue by korterling** [RinteRface/shinyMobile#229]
panels = tagList(
       f7Panel(title = "Left Panel", side = "left", theme = "light", "Blabla", effect = "cover"),
       f7Panel(title = "Right Panel", side = "right", theme = "dark", "Blabla", effect = "cover")
     ),

how to change the theme, how to set the default theme= light

**Comment by korterling** [comment]
any other theme?

**Comment by jpiaskowski** [comment]
These are the only 2 themes. If you want to adjust the colors, you can use the color parameter by adding a hexadecimal value (`color = "#ff1493") in the options list. If you want to make custom adjustments to the colors, look in to the [CSS variables](https://framework7.io/docs/css-variables) for the framework.
