### ISSUE TITLE
f7Page Issue

### ISSUE THREAD

**Issue by dnh-anh** [RinteRface/shinyMobile#233]
Hi,

Today I just run into a new issue I try to debug but no result:
I believe it's something related to the f7Page or my environment. I try both code between Window & MacOS still same issue

I'm using R4.1.3 & shinyMobile 0.9.1

Below is the simple code I use to check

Using f7Page, the server ran without any printting message

`
require(shiny)
require(shinyMobile)

ui <- f7Page("Hello")
server <- function(input, output, session) {
  print("Server Loaded")
} 
shinyApp(ui = ui, server = server)
`

Using fluidPage , the printting worked.

`
require(shiny)
require(shinyMobile)

ui <- fluidPage("Hello")
server <- function(input, output, session) {
  print("Server Loaded")
} 
shinyApp(ui = ui, server = server)
`

Really appreciate your advised

**Comment by DivadNojnarg** [comment]
Hi,

You can't use `f7Page` alone. According to the [documentation](https://rinterface.github.io/shinyMobile/reference/f7Page.html), the `...` parameter expects:

```r
... Slot for shinyMobile skeleton elements: \link{f7Appbar}, \link{f7SingleLayout},
#' \link{f7TabLayout}, \link{f7SplitLayout}.
```

Therefore, you must choose `f7SingleLayout` for instance like [here](https://rinterface.github.io/shinyMobile/reference/f7SingleLayout.html#examples).

**Comment by dnh-anh** [comment]
Sorry for make it not clear but I believe it worths commenting here also. The code works in productions with more information insides for shiny 1.7.1 but when I compiled at local for shiny 1.7.2, it only rendered the UI and the server failed. So it must be the issue from shiny 1.7.2 coz when I rolled back the local version, it works normally again
Bests
