### ISSUE TITLE
js code not working

### ISSUE THREAD

**Issue by korterling** [RinteRface/shinyMobile#243]
I have a script ,it work well in shiny ,but not work in shinymobile,what is wrong?
library(shiny)

ui <- fluidPage(
  tags$head(
    tags$script(
      HTML("
        $(document).on('click', '.my-link', function() {
          Shiny.setInputValue('link_clicked', this.id);
        });
      ")
    )
  ),
  
  fluidRow(
    column(12, align = "center",
           tags$a("click here", href = "#", class = "my-link", id = "link11", "link1"),
           tags$p("click here", href = "#", class = "my-link", id = "link21", "link2"),
           h2("click here", style = "color:#123456", class = "my-link", id = "link31", "link3")
  )
))

server <- function(input, output, session) {
  observeEvent(input$link_clicked, {
    link_id <- input$link_clicked
    showModal(
      modalDialog(
        link_id,
        easyClose = TRUE
      )
    )
   
  })
}

shinyApp(ui, server)

**Comment by korterling** [comment]
library(shiny)
library(shinyMobile)
library(apexcharter)
library(dplyr)
library(ggplot2)
library(shinyjs)
data("economics_long")
economics_long <- economics_long %>%
  group_by(variable) %>%
  slice((n()-100):n())


shinyApp(
  ui = f7Page(
    title = "My app",
 
    tags$head(
      tags$script(
        HTML("
        $(document).on('click', '.my-link', function() {
          Shiny.setInputValue('link_clicked', this.id);
        });
      ")
      )
    ),

    f7SingleLayout(
      navbar = f7Navbar(
        title = "Single Layout",
        hairline = TRUE,
        shadow = TRUE
      ),
      toolbar = f7Toolbar(
        position = "bottom",
        f7Link(label = "Link 1", href = "https://www.google.com"),
        f7Link(label = "Link 2", href = "https://www.google.com")
      ),
      
      tags$a("click here", href = "#", class = "my-link", id = "link11", "link1"),
      tags$p("click here", href = "#", class = "my-link", id = "link21", "link2"),
      h2("click here", style = "color:#123456", class = "my-link", id = "link31", "link3")
    )
  ),
  server = function(input, output) {
 
  }
)

**Comment by korterling** [comment]
@DivadNojnarg

**Comment by DivadNojnarg** [comment]
Hi, 

`{shinyMobile}` has its own modal function, `f7Dialog`:

You have to use the proper one:

```r
observeEvent(input$link_clicked, {
          link_id <- input$link_clicked
          f7Dialog(text = sprintf("Clicked linked is; %s", input$link_clicked), type = "alert")
  }
```

Full code below:

```r
library(shiny)
library(shinyMobile)
library(apexcharter)
library(dplyr)
library(ggplot2)
library(shinyjs)
data("economics_long")
economics_long <- economics_long %>%
    group_by(variable) %>%
    slice((n()-100):n())

shinyApp(
    ui = f7Page(
        title = "My app",
        
        tags$head(
            tags$script(
                HTML("
    $(document).on('click', '.my-link', function() {
      Shiny.setInputValue('link_clicked', this.id);
    });
  ")
            )
        ),
  
  f7SingleLayout(
      navbar = f7Navbar(
          title = "Single Layout",
          hairline = TRUE,
          shadow = TRUE
      ),
      toolbar = f7Toolbar(
          position = "bottom",
          f7Link(label = "Link 1", href = "https://www.google.com"),
          f7Link(label = "Link 2", href = "https://www.google.com")
      ),
      
      tags$a("click here", href = "#", class = "my-link", id = "link11", "link1"),
      tags$p("click here", href = "#", class = "my-link", id = "link21", "link2"),
      h2("click here", style = "color:#123456", class = "my-link", id = "link31", "link3")
  )
    ),
  server = function(input, output, session) {
      observeEvent(input$link_clicked, {
          link_id <- input$link_clicked
          f7Dialog(text = sprintf("Clicked linked is; %s", input$link_clicked), type = "alert")
  }
)})
```

**Comment by korterling** [comment]
Great, Can we customize the height and width of the f7Dialog?
@DivadNojnarg

**Comment by korterling** [comment]
Also, if there is a hyperlink(f7Link), when we click on this link, can we jump to the specified APP page? not a web site. thank you DivadNojnarg

**Comment by DivadNojnarg** [comment]
Yes for the text size you can pass whatever HTML tag you like, below is `h1`, ... and even add CSS:

```r
f7Dialog(text = h1(sprintf("Clicked linked is; %s", input$link_clicked)), type = "alert")
```

For the modal height you can't change the height yet because the methods don't have such parameter to pass extra information: https://v5.framework7.io/docs/dialog#alert. What you could do it add some CSS but this would apply to all modals, not to a specific one (so not very ideal).

**Comment by korterling** [comment]
Cool,Great,it is very interesting！
