### ISSUE TITLE
Tab labels not showing

### ISSUE THREAD

**Issue by SCasanova** [RinteRface/shinyMobile#249]
Hey. I'm using shinyMobile 1.0.0 and now my tab names don't render. If I switch to 0.9.1 they show up not on the current version. Quick example of issue below

``` r
if(interactive()){
    ui <- shinyMobile::f7Page(
        shinyMobile::f7SingleLayout(
            navbar = shinyMobile::f7Navbar(
                title = 'test'),
    shinyMobile::f7Tabs( 
        animated = T,
        swipeable = F,
        id = "tabset",
        style = 'strong',
        
        shinyMobile::f7Tab(
            tabName = "tab1",
            icon = shinyMobile::f7Icon("arrow_up_doc"),))))
    server <- function(input, output){}
    shinyApp(ui = ui, server = server)
}
```

<sup>Created on 2023-09-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by DivadNojnarg** [comment]
Hi,

In the 1.0.0, `f7Tabs` requires to pass the tab title in the [title](https://github.com/RinteRface/shinyMobile/blob/master/R/f7-tabs.R#L358) parameter:

```r
f7Tab(
  title = "Tab 1",
  tabName = "tab1",
  ...
)
```

This aligns with base `{shiny}` which used the same for `tabPanel`.

**Comment by SCasanova** [comment]
Good to know thanks
