### ISSUE TITLE
f7Button argument: strong not existing anymore

### ISSUE THREAD

**Issue by Jorammossink** [RinteRface/shinyMobile#271]
The f7Button documentation still carries the "strong" argument, but the function doesn't. I cannot find the documentation within the package; not sure how to update it.

**Comment by DivadNojnarg** [comment]
Hi,

I am not sure to understand. Are you using the latest shinyMobile version (2.0.1)?
The doc does not have `strong` argument anymore: https://shinymobile.rinterface.com/reference/button. `strong` is still needed by `f7Segment`, which is listed in the same category.

**Comment by Jorammossink** [comment]
True, I saw that it was listed under f7Segment; I must have mixed them up somehow.
