### ISSUE TITLE
How to see output of App in Mobile or Tablet view after Run APP ?

### ISSUE THREAD

**Issue by kmaheshkulkarni** [RinteRface/shinyMobile#37]

**Comment by DivadNojnarg** [comment]
Could you provide more detail? Thanks

**Comment by JohnCoene** [comment]
Open the app in Google Chrome then right click and select inspect then select the mobile in the bottom left.

<img width="866" alt="Screenshot 2019-12-04 at 16 02 33" src="https://user-images.githubusercontent.com/7833796/70153717-af0a5800-16af-11ea-8fd0-9056d6761cad.png">

**Comment by kmaheshkulkarni** [comment]
@JohnCoene Yup Your right.
But is there any option for R Window ?

**Comment by JohnCoene** [comment]
Had a wee think. It's true that it would be actually interesting to preview the app in such a setting. @DivadNojnarg do you thing we could wrap some of [devices.css](https://picturepan2.github.io/devices.css/) could be `device_iphone( f7SingleLayout(...))`. Would that work? It's by no means ideal but could help test things.

**Comment by DivadNojnarg** [comment]
The idea is interesting. In practice we need more than a css wrapper (user agent, ...)

**Comment by DivadNojnarg** [comment]
Here is a starting point: 

```r
preview_mobile <- function(appPath = NULL, url = NULL, port = 3838,
                           device = c(
                             "iphoneX",
                             "galaxyNote8",
                             "iphone8",
                             "iphonr8+",
                             "iphone5s",
                             "iphone5c",
                             "ipadMini",
                             "iphone4s",
                             "nexus5",
                             "lumia920",
                             "galaxyS5",
                             "htcOne",
                             "macbookPro"
                           ),
                           landscape = FALSE
) {

  # some tests
  if (!is.null(appPath) & !is.null(url)) stop("Choose either local or online app")
  if (is.null(appPath) & is.null(url)) stop("Choose at least one option")
  if (!is.null(appPath) & is.null(port)) stop("Please set a port when running locally")

  # set up the height
  appHeight <- switch (device,
                       "iphoneX" = 812,
                       "galaxyNote8" = 822,
                       "iphone8" = 500,
                       "iphonr8+" = 500,
                       "iphone5s" = 500,
                       "iphone5c" = 500,
                       "ipadMini" = 500,
                       "iphone4s" = 500,
                       "nexus5" = 500,
                       "lumia920" = 500,
                       "galaxyS5" = 500,
                       "htcOne" = 500,
                       "macbookPro" = 500
  )

  # run the shiny app to test
  message("Copy in your terminal (not the R console): R -e \"shiny::runApp('", appPath, "', port = ", port, ")\"")
  invisible(readline(prompt="Press [enter] to continue"))

  # iframe
  iframeApp <- shiny::tags$iframe(
    width = "100%",
    src = if (!is.null(appPath)) {
      paste0("http://127.0.0.1:", port)
    } else {
      url
    },
    allowfullscreen = "",
    frameborder = "0",
    scrolling = "no",
    height = paste0(appHeight, "px") # height depends on the choosen device!
  )

  # master app
  ui <- shiny::fluidPage(
    shiny::tags$head(
      shiny::includeCSS(path = system.file("framework7-5.1.3/devices/devices.min.css", package = "shinyMobile"))
    ),
    # container for preview app
    shiny::fluidRow(align = "center", create_app_container(iframeApp, skin = device))
  )

  server <- function(input, output, session) {}
  shiny::runApp(list(ui = ui, server = server), port = 5656, launch.browser = TRUE)
}




create_app_container <- function(..., skin) {
  tag <- if (skin == "iphoneX") {
    print("fuck")
    shiny::tags$div(
      class = "marvel-device iphone-x",
      shiny::tags$div(class = "top-bar"),
      shiny::tags$div(class = "sleep"),
      shiny::tags$div(class = "bottom-bar"),
      shiny::tags$div(class = "volume"),
      shiny::tags$div(
        class = "overflow",
        shiny::tags$div(class = "shadow shadow--tr"),
        shiny::tags$div(class = "shadow shadow--tl"),
        shiny::tags$div(class = "shadow shadow--br"),
        shiny::tags$div(class = "shadow shadow--bl")
      ),
      shiny::tags$div(class = "inner-shadow"),
      shiny::tags$div(class = "screen", ...)
    )
  } else if (skin == "galaxyNote8") {
    shiny::tags$div(
      class = "marvel-device note8",
      shiny::tags$div(class = "inner"),
      shiny::tags$div(class = "overflow", shiny::tags$div(class = "shadow")),
      shiny::tags$div(class = "speaker"),
      shiny::tags$div(class = "sensors"),
      shiny::tags$div(class = "more-sensors"),
      shiny::tags$div(class = "sleep"),
      shiny::tags$div(class = "volume"),
      shiny::tags$div(class = "camera"),
      shiny::tags$div(class = "screen", ...)
    )

  }
  return(tag)
}
```

The function could be called as follows:

```r
preview_mobile(appPath = "~/whatever", device = "galaxyNote8")
```

You also have to run the other app in a separate terminal, on a different port.

**Comment by kmaheshkulkarni** [comment]
> Had a wee think. It's true that it would be actually interesting to preview the app in such a setting. @DivadNojnarg do you thing we could wrap some of [devices.css](https://picturepan2.github.io/devices.css/) could be `device_iphone( f7SingleLayout(...))`. Would that work? It's by no means ideal but could help test things.

I was tried it but its not working....

**Comment by kmaheshkulkarni** [comment]
> Here is a starting point:
> 
> ```r
> preview_mobile <- function(appPath = NULL, url = NULL, port = 3838,
>                            device = c(
>                              "iphoneX",
>                              "galaxyNote8",
>                              "iphone8",
>                              "iphonr8+",
>                              "iphone5s",
>                              "iphone5c",
>                              "ipadMini",
>                              "iphone4s",
>                              "nexus5",
>                              "lumia920",
>                              "galaxyS5",
>                              "htcOne",
>                              "macbookPro"
>                            ),
>                            landscape = FALSE
> ) {
> 
>   # some tests
>   if (!is.null(appPath) & !is.null(url)) stop("Choose either local or online app")
>   if (is.null(appPath) & is.null(url)) stop("Choose at least one option")
>   if (!is.null(appPath) & is.null(port)) stop("Please set a port when running locally")
> 
>   # set up the height
>   appHeight <- switch (device,
>                        "iphoneX" = 812,
>                        "galaxyNote8" = 822,
>                        "iphone8" = 500,
>                        "iphonr8+" = 500,
>                        "iphone5s" = 500,
>                        "iphone5c" = 500,
>                        "ipadMini" = 500,
>                        "iphone4s" = 500,
>                        "nexus5" = 500,
>                        "lumia920" = 500,
>                        "galaxyS5" = 500,
>                        "htcOne" = 500,
>                        "macbookPro" = 500
>   )
> 
>   # run the shiny app to test
>   message("Copy in your terminal (not the R console): R -e \"shiny::runApp('", appPath, "', port = ", port, ")\"")
>   invisible(readline(prompt="Press [enter] to continue"))
> 
>   # iframe
>   iframeApp <- shiny::tags$iframe(
>     width = "100%",
>     src = if (!is.null(appPath)) {
>       paste0("http://127.0.0.1:", port)
>     } else {
>       url
>     },
>     allowfullscreen = "",
>     frameborder = "0",
>     scrolling = "no",
>     height = paste0(appHeight, "px") # height depends on the choosen device!
>   )
> 
>   # master app
>   ui <- shiny::fluidPage(
>     shiny::tags$head(
>       shiny::includeCSS(path = system.file("framework7-5.1.3/devices/devices.min.css", package = "shinyMobile"))
>     ),
>     # container for preview app
>     shiny::fluidRow(align = "center", create_app_container(iframeApp, skin = device))
>   )
> 
>   server <- function(input, output, session) {}
>   shiny::runApp(list(ui = ui, server = server), port = 5656, launch.browser = TRUE)
> }
> 
> 
> 
> 
> create_app_container <- function(..., skin) {
>   tag <- if (skin == "iphoneX") {
>     print("fuck")
>     shiny::tags$div(
>       class = "marvel-device iphone-x",
>       shiny::tags$div(class = "top-bar"),
>       shiny::tags$div(class = "sleep"),
>       shiny::tags$div(class = "bottom-bar"),
>       shiny::tags$div(class = "volume"),
>       shiny::tags$div(
>         class = "overflow",
>         shiny::tags$div(class = "shadow shadow--tr"),
>         shiny::tags$div(class = "shadow shadow--tl"),
>         shiny::tags$div(class = "shadow shadow--br"),
>         shiny::tags$div(class = "shadow shadow--bl")
>       ),
>       shiny::tags$div(class = "inner-shadow"),
>       shiny::tags$div(class = "screen", ...)
>     )
>   } else if (skin == "galaxyNote8") {
>     shiny::tags$div(
>       class = "marvel-device note8",
>       shiny::tags$div(class = "inner"),
>       shiny::tags$div(class = "overflow", shiny::tags$div(class = "shadow")),
>       shiny::tags$div(class = "speaker"),
>       shiny::tags$div(class = "sensors"),
>       shiny::tags$div(class = "more-sensors"),
>       shiny::tags$div(class = "sleep"),
>       shiny::tags$div(class = "volume"),
>       shiny::tags$div(class = "camera"),
>       shiny::tags$div(class = "screen", ...)
>     )
> 
>   }
>   return(tag)
> }
> ```
> 
> The function could be called as follows:
> 
> ```r
> preview_mobile(appPath = "~/whatever", device = "galaxyNote8")
> ```
> 
> and you also have to run the other app in a separate terminal, on a different port.
> 
> Alternatively, if your app is running online:
> 
> ```r
> preview_mobile(url = "https://dgranjon.shinyapps.io/miniUI2DemoMd", device = "galaxyNote8")
> ```

I will try this let's see.... but it's an interesting @DivadNojnarg great work bro
