### ISSUE TITLE
issue 10 still open? some icons still not rendering. 

### ISSUE THREAD

**Issue by McCartneyAC** [RinteRface/shinyMobile#46]
e.g. "perspective", "function", "chart_bar_alt_fill", etc. 

Only properly working icons tested so far: "book" and "list_number"

**Comment by DivadNojnarg** [comment]
I am afraid icons are entirely bugged in framework7. Today I tried to apply the green color to some icons, which render in blue...

**Comment by DivadNojnarg** [comment]
Could you try again with the development version? An important update was pushed by @pvictor and it should solve you problem.

**Comment by pvictor** [comment]
Haven't tested all, but icons available on this page : https://framework7.io/icons/ should work with `old = FALSE`, e.g. in your console, icon will appear in viewer : 

```r
f7Icon("chart_bar_alt_fill", old = FALSE)
```

**Comment by SIBeckers** [comment]
I think f7Panel is also affected by this issue.
shinyMobile version = 0.5.0.9000
bars icon rendered as text.
See f7Panel example code as an example of the issue.

**Comment by DivadNojnarg** [comment]
Closed in @53565060
