### ISSUE TITLE
extend f7Search to f7Expandablecards

### ISSUE THREAD

**Issue by rodrigoheck** [RinteRface/shinyMobile#47]
The way I see it, f7Search works fine for f7List groups. It would be really nice if this worked for cards' titles as well. :)

**Comment by DivadNojnarg** [comment]
Hi Rodrigo, this is a framework7 restriction (https://framework7.io/docs/searchbar.html). In the past, I tried to adapt it for other components, without success.

**Comment by DivadNojnarg** [comment]
Now with the general rework in rc 1.0.0, you should be able to target anything!
