### ISSUE TITLE
Need a better hex 

### ISSUE THREAD

**Issue by DivadNojnarg** [RinteRface/shinyMobile#50]

**Comment by JohnCoene** [comment]
Let me gives this a go this weekend, any ideas?

**Comment by JohnCoene** [comment]
![shinymobile](https://user-images.githubusercontent.com/7833796/72217871-4dea6580-3534-11ea-8430-583a4ffaeaba.png)
thoughts?

**Comment by JohnCoene** [comment]
Obviously inspired by the original shiny sticker.

**Comment by JohnCoene** [comment]
This probably makes the mobile more evident.
![shinymobile](https://user-images.githubusercontent.com/7833796/72217925-fc8ea600-3534-11ea-9cad-c626062f2977.png)

**Comment by JohnCoene** [comment]
Lats sticker in PR #51
