### ISSUE TITLE
f7Gauge valueText

### ISSUE THREAD

**Issue by tanho63** [RinteRface/shinyMobile#84]
Hi all! In [one of the recent commits](https://github.com/RinteRface/shinyMobile/commit/be50ea2d76077b31e4f6cb144e1f119be36f0f05), valueText was removed as a parameter from f7Gauge with the comment

> It does not make sense that the value can be accidentally different from the text displayed. valueText is then an internal parameter.

I think it would be better to try to default valueText to be equal to the value parameter but allow for customization - this gives it a natural default but also some easy flexibility for developers. 

In the [documentation](https://framework7.io/docs/gauge.html) for Gauge there are several examples of useful "value-text" customizations - namely, adding units, currency symbols, or showing the raw numbers used in the proportion. 

![image](https://user-images.githubusercontent.com/38083823/76153787-50ce8600-609f-11ea-8c75-47d215cec6a7.png)

In my case, I'd like to use `valueText` in my app because I want to use it as a graphic for "balance from a trade" and would show difference from 50% (i.e. perfectly equal). 

Thus in the image below I'd use 40% as the "value parameter" but would want to display "10% in favor of team B" - and it would be nice to be able to show that with the 10% nested into the centre of the gauge. 

![image](https://user-images.githubusercontent.com/38083823/76153792-5b891b00-609f-11ea-963e-6be09154fa14.png)

**Comment by DivadNojnarg** [comment]
Hi Tan,
if you already have the code, you may propose a pull request!
