### ISSUE TITLE
updateF7AutoComplete acts oddly with one-element lists

### ISSUE THREAD

**Issue by tanho63** [RinteRface/shinyMobile#90]
Hi @DivadNojnarg  - just stumbled on choices being missing from updateF7AutoComplete and wondered if you had insight on why this was a problem in your initial code: 

```
  // see updateF7AutoComplete
  receiveMessage: function(el, data) {
    //var a = app.autocomplete.get($(el));
    // update choices
    //if (data.hasOwnProperty('choices')) {

    //}
    // Update value
    if (data.hasOwnProperty('value')) {
      this.setValue(el, data.value);
    }
  },
```

**Comment by DivadNojnarg** [comment]
This was broken at that time. Now, framework7 has been updated so it may work (or not).

**Comment by tanho63** [comment]
Hmm..I haven't tried adding the choices feature yet but updating the "value" is acting a little oddly with a character vector of length one. It seems to work okay with character vectors length two.

Video of issue: https://streamable.com/nxur3

App - https://apps.dynastyprocess.com/calc/
Code - https://github.com/tanho63/dynastyprocess-apps/blob/dev/calc/app.R

I'm trying to change inputs upstream of the reactive dataframe that is used to generate the f7AutoComplete - and it seems to be updating the values correctly as long as the vector is length two or more, but somehow it's sending each character of the string as individual objects if the vector is length one...

I *think* this is a JS thing but my JS abilities are very very limited!

**Comment by tanho63** [comment]
Stumbled on this comment by (Yihui? Joe Cheng?) in the DT package and it seems to fix the problem! 
![image](https://user-images.githubusercontent.com/38083823/77428914-3e4a9100-6daf-11ea-9f87-981d60b70d68.png)

I'll make a pull request to fix the issue later today, unless you guys get to it sooner :) @DivadNojnarg

**Comment by DivadNojnarg** [comment]
Thanks!
