### ISSUE TITLE
Title Element over written by f7 CSS?

### ISSUE THREAD

**Issue by davis3tnpolitics** [RinteRface/shinyMobile#96]
Hi Tim,

Thank you so much for this amazing package. Question: in the newest dev version, is the initialization of the splashscreens working? I just updated last Friday and I can't even get a title div to show my favicon. Thoughts on the issue here?

tags$head(
        tags$title("title"),
        tags$link(rel="icon", type="image", href="./favicon.ico")
    )

**Comment by DivadNojnarg** [comment]
Please have a look at the new f7Page function. It has 3 new parameters, among which favicon. It is best practice to put your favicon in a www/ folder. See [here](https://github.com/DivadNojnarg/deminR/blob/master/R/app_ui.R) for a real life example.
