### ISSUE TITLE
shiny::f7Gallery() not working

### ISSUE THREAD

**Issue by davidodongojr** [RinteRface/shinyMobile#97]
Warning in file(filename, "r", encoding = encoding) :
  cannot open file '.../R/win-library/3.5/shinyMobile/examples/gallery/tabstabBtns.R': No such file or directory

any help? something seems wrong with the path

**Comment by DivadNojnarg** [comment]
I did not manage to reproduce the issue

**Comment by davidodongojr** [comment]
Sorry I fixed it....the forward slash at the end of the path was not being recognised so  had to paste() it in.

I tried running the shinyMobile::f7Gallery() command to see the types of input
